### ISSUE TITLE
Response is slow

### ISSUE THREAD

**Issue by Andreotti100** [Net-time/Domoticz_Shelly_Plugin#1]
The response is slow. Very slow.

**Comment by Net-time** [comment]
Hello.
This is by design as I usually only read switch states and temperatures. I think the loop is 10 seconds at the moment.
But I can add a setting for how often the loop fires (Heartbeat) now that I know I may have users.

**Comment by Net-time** [comment]
Actually bypassed the loop entirely, should work fine for switching now.

**Comment by Andreotti100** [comment]
That's so much better.
Thanks buddy!
